### ISSUE TITLE
Use Morgan for request logs

### ISSUE THREAD

**Issue by shankha-solulab** [M-Ubaid-Asif/typescript-uber-api#11]
https://github.com/M-Ubaid-Asif/typescript-uber-api/blob/40ad709c1b1434473f56584351e805bec8d61b13/src/app.ts#L10

**Comment by M-Ubaid-Asif** [comment]
issue resolved! added morgan for request log

> https://github.com/M-Ubaid-Asif/typescript-uber-api/blob/40ad709c1b1434473f56584351e805bec8d61b13/src/app.ts#L10
